server:
  port: 8030

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:116.63.145.108}:${MYSQL_PORT:3306}/open_admin?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:xxxxxxxxxxxxxxxx}

resource:
  upload-location: /www/wwwroot/open_admin
  server-url: http://xxxxx/open_admin

wx:
  mini-app:
    appId: xxxxxxxxxxxxxxxx
    appSecret: xxxxxxxxxxxxxxxx

server-url: http://116.63.145.108:8030