server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:116.63.145.108}:${MYSQL_PORT:3306}/open_admin?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:xxxxxxxxxxxxxxxx}

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开始sql打印

resource:
  upload-location: D:\\uploads\\open_admin
  server-url: http://localhost:8020/open_admin

wx:
  mini-app:
    appId: xxxxxxxxxxxxxxxx
    appSecret: xxxxxxxxxxxxxxxx

server-url: http://localhost:8020

