server:
  port: 8030

spring:
  datasource:
    url: jdbc:mysql://116.63.145.108:3306/open_admin?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false
    username: root
    password: 9bee4a941bd1e791

resource:
  upload-location: /www/wwwroot/cdn.langyiquan.com/open_admin
  server-url: http://cdn.langyiquan.com/open_admin

wx:
  mini-app:
    appId: wx2f9338a8bc87bdd6
    appSecret: 261716a22b733fa0e129b375648347ed1

server-url: http://116.63.145.108:8030