apiVersion: v1
kind: Service
metadata:
  name: open-admin-front-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 32557
  selector:
    run: open-admin-front
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-admin-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: open-admin-front
  template:
    metadata:
      labels:
        run: open-admin-front
    spec:
      containers:
        - name: open-admin-front
          image: 192.168.1.100:8082/l-docker/open-admin-front:latest
          ports:
            - containerPort: 80
